<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRjxz81x\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRjxz81x/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerRjxz81x.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerRjxz81x\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerRjxz81x\appProdProjectContainer([
    'container.build_hash' => 'Rjxz81x',
    'container.build_id' => '27ca93c2',
    'container.build_time' => 1585230749,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRjxz81x');
