<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLx3lo2v\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLx3lo2v/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerLx3lo2v.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerLx3lo2v\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerLx3lo2v\appProdProjectContainer([
    'container.build_hash' => 'Lx3lo2v',
    'container.build_id' => 'bacd3e92',
    'container.build_time' => 1585570184,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLx3lo2v');
